var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,e,c){b instanceof String&&(b=String(b));for(var f=b.length,k=0;k<f;k++){var g=b[k];if(e.call(c,g,k,b))return{i:k,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,c){b!=Array.prototype&&b!=Object.prototype&&(b[e]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,e,c,f){if(e){c=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var k=b[f];k in c||(c[k]={});c=c[k]}b=b[b.length-1];f=c[b];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
$(function(){function b(){_mArea.animate({"margin-left":-1*_mArea.width()+"px"},500,"easeOutQuint",function(){y.fadeOut(200);_mArea.hide()});t.removeClass("noscroll");w.fadeOut();p.children("ul").hide()}function e(){n=g.outerWidth();if(768>n)y.hide(),w.hide(),_mArea.css({"margin-left":-1*_mArea.width()+"px"}),A.on({mouseenter:function(){$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")},mouseleave:function(){$(this).parent().siblings("ul").hide();$(this).children("ul").stop(!0,!0).slideUp("600",
"easeOutQuint")}}),p.off().on("mouseenter,mouseleave"),p.on("touchstart",function(){$(this).off("mouseenter,mouseleave")}),A.off().on("click",function(a){$(this).siblings("li").find("ul").stop(!0,!0).slideUp("600","easeOutQuint");$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")}),K.off().on("click",function(a){$(this).siblings("li").children("ul").stop(!0,!0).slideUp("600","easeOutQuint");$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")}),L.off().on("click",function(a){a.preventDefault()}),
$(".sidebar .menu .hasChild").children("a").off().on("click",function(a){a.preventDefault()}),B.on({mouseenter:function(){$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")},mouseleave:function(){$(this).parent().siblings("ul").hide();$(this).children("ul").stop(!0,!0).slideUp("600","easeOutQuint")}}),u.off().on("mouseenter,mouseleave"),u.on("touchstart",function(){$(this).off("mouseenter,mouseleave")}),B.off().on("click",function(a){$(this).siblings("li").find("ul").stop(!0,!0).slideUp("600",
"easeOutQuint");$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")}),M.off().on("click",function(a){$(this).siblings("li").children("ul").stop(!0,!0).slideUp("600","easeOutQuint");$(this).children("ul").stop(!0,!0).slideDown("600","easeOutQuint")}),N.off().on("click",function(a){a.preventDefault()}),$(".sidebar .megamenu .hasChild").children("a").off().on("click",function(a){a.preventDefault()}),t.off("touchmove"),$(".m_search").hide(),$(".language").find("ul").hide();else{b();t.removeClass("noscroll");
C.prependTo(".header .container");x.appendTo(".header .container");m.appendTo(".header .container");q.appendTo(".header .container");x.removeClass("m_search");$(".m_search").hide();x.show();v=!1;$(".language").find("ul").hide();p.on({mouseenter:function(){$(this).children("ul").stop(!0,!1).fadeIn()},mouseleave:function(){$(this).parent().siblings("ul").hide();$(this).children("ul").stop(!0,!1).fadeOut()}});p.off("click");u.on({mouseenter:function(){$(this).children("ul").stop(!0,!1).fadeIn()},mouseleave:function(){$(this).parent().siblings("ul").hide();
$(this).children("ul").stop(!0,!1).fadeOut()}});u.off("click");$(".megamenu").children("ul").children("li").children("ul").hide();if(0<m.lenght)p.on({mouseenter:function(){$(this).children("ul").stop(!0,!1).fadeIn()},mouseleave:function(){$(this).parent().siblings("ul").hide();$(this).children("ul").stop(!0,!1).fadeOut()}});if(0<q.lenght)u.on({mouseenter:function(){$(this).children("ul").stop(!0,!1).fadeIn()},mouseleave:function(){$(this).parent().siblings("ul").hide();$(this).children("ul").stop(!0,
!1).fadeOut()}})}}function c(){$(".tabs").each(function(){function a(a){var c=$(this),r=h.offset().top,O=c.index()/2;r=r+d*O-z;b.removeClass("active");c.addClass("active");768>=n?(b.not(".active").next().slideUp(),c.next().slideDown(),$("html,body").stop(!0,!1).animate({scrollTop:r})):(b.not(".active").next().hide(),c.next().show(),e=c.next().innerHeight(),h.height(e+d));a.preventDefault()}var h=$(this),b=h.find(".tabItem"),r=h.find(".tabContent"),c=h.width(),d=b.outerHeight(),e=h.find(".active").next().innerHeight(),
f=b.length;h.find(".active").next(".tabContent").show();768<=n?(r.css("top",d),h.height(e+d),r=(c-0*(f-1))/f,b.width(r).css("margin-left",0),b.first().css("margin-left",0),b.last().css({position:"absolute",top:0,right:0}).width(r)):(h.css("height","auto"),b.width(c),b.css("margin-left",0).last().css("position","relative"));b.focus(a);b.click(a)})}function f(a,h,b){if(b){var c=new Date;c.setTime(c.getTime()+864E5*b);b="; expires="+c.toGMTString()}else b="";document.cookie=a+"="+h+b+"; path=/"}function k(){if(0==
$("table").parents(".table_list").length&&0==$("table").parents(".fix_th_table").length&&0==$(this).parent("form").length&&0<$(".scroltable-wrapper").length){var a=Math.floor($(".scroltable-wrapper").offset().top),b=Math.floor($(this).scrollTop());b>a-230?($(".scroltable-wrapper .tablearrow_left").css("display","block"),$(".scroltable-wrapper .tablearrow_left").css({top:b-a+220},100,"easeOutQuint"),$(".scroltable-wrapper .tablearrow_right").css("display","block"),$(".scroltable-wrapper .tablearrow_right").css({top:b-
a+220},100,"easeOutQuint")):($(".scroltable-wrapper .tablearrow_left").css({top:"10px",display:"none"}),$(".scroltable-wrapper .tablearrow_right").css({top:"10px",display:"none"}))}}document.createElement("picture");document.documentElement.addEventListener("gesturestart",function(a){a.preventDefault()},!1);var g=$(window),n=g.outerWidth();g.height();var t=$("body");$("html").removeClass("no-js");1<$(".navigation ul").length&&$(".navigation ul:nth-child(1)").addClass("left_nav");$(".navigation").has(".language").addClass("have_language");
var m=$(".menu"),q=$(".megamenu");m.find("li").has("ul").addClass("hasChild");q.find("li").has("ul").addClass("hasChild");var p=m.find("li.hasChild"),u=q.children("ul").children("li.hasChild");t.prepend('<aside class="sidebar"><div class="m_area"><button type="button" class="sidebarClose">\u95dc\u9589</button></div><div class="menu_overlay"></div></aside>');$("header .container").prepend('<button type="button" class="sidebarCtrl">\u5074\u6b04\u9078\u55ae</button><button type="button" class="searchCtrl">\u67e5\u8a62</button>');
var y=$(".sidebar"),x=$(".search"),C=$(".navigation"),d=$(".sidebarClose"),D=$(".sidebarCtrl"),w=$(".menu_overlay");_mArea=$(".m_area");D.append("<span></span><span></span><span></span>");var v=!1;D.click(function(a){y.show();_mArea.show();_mArea.animate({"margin-left":0},400,"easeOutQuint");t.addClass("noscroll");w.fadeIn();$(".m_search").hide();v=!1;a.preventDefault()});w.add(d).off().click(function(){b()});w.off("mouseenter");p.children("a").keyup(function(){$(this).siblings("ul").fadeIn();$(this).parent("li").siblings().focus(function(){$(this).hide()})});
m.find("li").keyup(function(){$(this).siblings().children("ul").hide()});m.find("li:last>a").focusout(function(){m.find("li ul").hide()});u.children("a").keyup(function(){$(this).siblings("ul").fadeIn();$(this).siblings("ul").find("ul").fadeIn();$(this).parent("li").siblings().focus(function(){$(this).hide()})});q.children("ul").children("li").keyup(function(){$(this).siblings().children("ul").hide()});q.find("li:last>a").focusout(function(){m.find("li ul").hide()});C.clone().prependTo(_mArea);m.clone().prependTo(_mArea);
q.clone().prependTo(_mArea);x.clone().prependTo(t).addClass("m_search");var A=$("aside .menu ul").children("li.hasChild"),K=$("aside .menu ul ul").children("li.hasChild"),L=$("aside .menu ul ul ul").children("li.hasChild");p.first().children("ul").outerWidth();var B=$("aside .megamenu ul").children("li.hasChild"),M=$("aside .megamenu ul ul").children("li.hasChild"),N=$("aside .megamenu ul ul ul").children("li.hasChild");u.first().children("ul").outerWidth();var E;g.bind("load resize",function(a){clearTimeout(E);
E=setTimeout(function(){e()},50)});e();d=$(".searchCtrl");$(".m_search").hide();d.off().on("click",function(a){v?($(".m_search").hide(),v=!1):($(".m_search").stop(!0,!1).slideDown("400","easeOutQuint"),g.off("resize"),v=!0)});$(".main").off().on("click touchend",function(a){$(".m_search").hide();v=!1});var z=Math.floor($(".header").outerHeight(!0));if(0<$("header .menu").length){var P=Math.floor($("header .menu").offset().top);z=Math.floor($(".header").outerHeight(!0));menuH=Math.floor(m.outerHeight(!0));
$(window).bind("load scroll resize",function(a){n=g.outerWidth();768<=n&&$(this).scrollTop()>P?($(".header").addClass("fixed"),$(".header").css("margin-top",-136)):($(".header").removeClass("fixed"),$(".header").css("margin-top",0),$(".main").css("margin-top",0))})}if(0<$("header .megamenu").length){var Q=Math.floor($("header .megamenu").offset().top);z=Math.floor($(".header").outerHeight(!0));megamenuH=Math.floor(q.outerHeight(!0));$(window).bind("load scroll resize",function(a){n=g.outerWidth();
768<=n&&$(this).scrollTop()>Q?($(".header").addClass("fixed"),$(".header").css("margin-top",-136)):($(".header").removeClass("fixed"),$(".header").css("margin-top",0),$(".main").css("margin-top",0))})}$('[class*="notice"] a.close').click(function(a){$(this).parent('[class*="notice"]').hide();a.preventDefault()});$(".accordion").each(function(){$(this).find(".accordion-content").hide();$(this).children("ul").children("li").children("a").each(function(){function a(a){$(this).parent("li").siblings().children("a").removeClass("active");
$(this).toggleClass("active");$(this).parent("li").siblings().children(".accordion-content").slideUp();$(this).next(".accordion-content").slideToggle();a.preventDefault()}$(this).click(a);$(this).keyup(a)})});$(".btn-fatfooter").click(function(a){$(this).parent(".container").find("nav>ul>li>ul").stop(!0,!0).slideToggle(function(){$(this).is(":visible")?($(".btn-fatfooter").html("\u6536\u5408/CLOSE"),$(".btn-fatfooter").attr("name","\u6536\u5408\u9078\u55ae/CLOSE")):($(".btn-fatfooter").html("\u5c55\u958b/OPEN"),
$(".btn-fatfooter").attr("name","\u5c55\u958b\u9078\u55ae/OPEN"))});$(this).stop(!0,!0).toggleClass("close")});if(0<$(".has_lightbox").length){var G=function(){1<l+1?l--:l=F-1;THUMB_PIC=$(".album .thumbnail").eq(l).find(".img-container picture source:first").attr("data-srcset");THUMB_H3=$(".album .thumbnail").eq(l).find(".img-container img").attr("alt");$(".album .lightbox .caption").html(THUMB_H3);$(".album .lightbox img").hide();$(".album .lightbox img").fadeIn();$(".album .lightbox img").attr("src",
THUMB_PIC)},H=function(){l+1<F?l++:l=0;THUMB_PIC=$(".album .thumbnail").eq(l).find(".img-container picture source:first").attr("data-srcset");THUMB_H3=$(".album .thumbnail").eq(l).find(".img-container img").attr("alt");$(".album .lightbox .caption").html(THUMB_H3);$(".album .lightbox img").hide();$(".album .lightbox img").fadeIn();$(".album .lightbox img").attr("src",THUMB_PIC)};$(".album").append('<div class="lightbox"><a href="#" class="light_close">\u95dc\u9589</a><a href="#" class="light_prev">\u4e0a\u4e00\u5f35</a><a href="#" class="light_next">\u4e0b\u4e00\u5f35</a><img src="" alt=""><div class="galler_overlay"></div></div>');
$(".album .lightbox").hide();$(".light_close").click(function(a){$(".album .lightbox").hide();$("body").removeClass("noscroll");$(".album .lightbox .caption").html("")});$(".album .lightbox .galler_overlay").click(function(a){$(".album .lightbox").hide();$("body").removeClass("noscroll");$(".album .lightbox .caption").html("")});$(".album .lightbox img").attr("src");var l=0;$(".album a").click(function(a){a.preventDefault()});$(".album .thumbnail a").each(function(a){$(this).click(function(b){var h=
$(this).find(".img-container img").attr("alt");$("body").addClass("noscroll");$(".album .lightbox").append('<div class="caption">'+h+"<div>");THUMB_PIC=$(this).find(".img-container img").attr("data-src");$(".album .lightbox img").attr("src",THUMB_PIC);$(".album .lightbox").fadeIn();$(".album .lightbox .galler_overlay").fadeIn();l=a;b.preventDefault()})});var F=$(".album .thumbnail").length;$(".album .light_next").click(function(a){H();a.preventDefault()});$(".album .light_prev").click(function(a){G();
a.preventDefault()});$("body").keydown(function(a){37==a.keyCode?G():39==a.keyCode?H():27==a.keyCode&&($(".album .lightbox").hide(),$("body").removeClass("noscroll"))})}var I;g.resize(function(){clearTimeout(I);I=setTimeout(function(){n=g.outerWidth();c()},50)});$(".tabs>.tabItem:first-child>a").trigger("click");c();$(window).bind("scroll",function(){200<$(this).scrollTop()?$(".scrollToTop").fadeIn():$(".scrollToTop").fadeOut()});$(".scrollToTop").click(function(a){$("html, body").animate({scrollTop:0},
400,"easeOutExpo");$("a.goCenter").focus();a.preventDefault()});$(".scrollToTop").keydown(function(a){t.find("a.goCenter").focus();a.preventDefault()});/msie|Trident.*rv[ :]*11\./gi.test(window.navigator.userAgent)&&$(".img-container").each(function(){var a=$(this).find("img").attr("data-src"),b=$(this);b.has(".none").addClass("ie-object-none");b.has(".none").css("backgroundImage","url("+a+")");b.has(".cover").addClass("ie-object-cover");b.has(".cover").css("backgroundImage","url("+a+")");b.has(".fill").addClass("ie-object-fill");
b.has(".fill").css("backgroundImage","url("+a+")");b.has(".contain").addClass("ie-object-contain");b.has(".contain").css("backgroundImage","url("+a+")")});$('input[type="checkbox"]').off().click(function(a){$(this).blur()});$(document).on("change",".check_file",function(){for(var a=[],b=$(this).get(0).files.length,c=0;c<$(this).get(0).files.length;++c)a.push($(this).get(0).files[c].name);2<b?(a.join(", "),$(this).closest(".upload_grp").find(".upload_file").attr("value",b+" files selected")):$(this).closest(".upload_grp").find(".upload_file").attr("value",
a)});$(".function_panel .share").children("ul").hide();$(".function_panel .share").prepend('<a href="#" class="shareButton">share\u5206\u4eab\u6309\u9215</a>');d=$(".shareButton");d.off().click(function(a){$(this).siblings("ul").stop(!0,!0).slideToggle();a.preventDefault()});d.keyup(function(a){$(this).siblings("ul").stop(!0,!0).slideDown()});$(".function_panel .share").find("li:last>a").focusout(function(a){$(this).parent().parent("ul").hide()});$(document).on("touchend click",function(a){var b=
$(".function_panel .share");b.is(a.target)||0!==b.has(a.target).length||$(".function_panel .share ul").hide()});$(".font_size").find(".small").click(function(a){$(this).parent("li").siblings("li").find("a").removeClass("active");$(".innerpage").removeClass("large_size").addClass("small_size");$(this).addClass("active");a.preventDefault();f("FontSize","small",356)});$(".font_size").find(".medium").click(function(a){$(this).parent("li").siblings("li").find("a").removeClass("active");$(".innerpage").removeClass("large_size small_size");
$(this).addClass("active");a.preventDefault();f("FontSize","medium",356)});$(".font_size").find(".large").click(function(a){$(this).parent("li").siblings("li").find("a").removeClass("active");$(".innerpage").removeClass("small_size").addClass("large_size");$(this).addClass("active");a.preventDefault();f("FontSize","large",356)});window.onload=function(a){a:{var b=document.cookie.split(";");for(var c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf("FontSize=")){b=
d.substring(9,d.length);break a}}b=null}"small"==b?($(".font_size").find(".small").parent("li").siblings("li").find("a").removeClass("active"),$(".innerpage").removeClass("large_size medium_size").addClass("small_size"),$(".font_size").find(".small").addClass("active")):"large"==b?($(".font_size").find(".large").parent("li").siblings("li").find("a").removeClass("active"),$(".innerpage").removeClass("small_size medium_size").addClass("large_size"),$(".font_size").find(".large").addClass("active")):
($(".font_size").find(".medium").parent("li").siblings("li").find("a").removeClass("active"),$(".innerpage").removeClass("large_size small_size"),$(".font_size").find(".medium").addClass("active"));a.preventDefault()};$(".category").find("a").off().click(function(a){$(this).parent("li").siblings().find("a").removeClass("active");$(this).addClass("active")});$(document).on("keydown",function(a){a.altKey&&83==a.keyCode&&($("html, body").animate({scrollTop:0},200,"easeOutExpo"),$(".search").find('input[type="text"]').focus());
a.altKey&&85==a.keyCode&&($("html, body").animate({scrollTop:0},200,"easeOutExpo"),$("header").find(".accesskey").focus());a.altKey&&67==a.keyCode&&($("html, body").stop(!0,!0).animate({scrollTop:$(".main").find(".accesskey").offset().top-70},800,"easeOutExpo"),$(".main").find(".accesskey").focus());a.altKey&&90==a.keyCode&&($("html, body").stop(!0,!0).animate({scrollTop:$("footer").find(".accesskey").offset().top},800,"easeOutExpo"),$("footer").find(".accesskey").focus())});$("html")[0].hasAttribute("labg")&&
(d=$("html").attr("lang"),"zh"==d.substring(0,2)?($(".slick-prev").attr("title","\u4e0a\u4e00\u7b46"),$(".slick-next").attr("title","\u4e0b\u4e00\u7b46")):"zh"!==d.substring(0,2)&&($(".slick-prev").attr("title","previous"),$(".slick-next").attr("title","next")));d=$("html").attr("lang");"zh"==d.substring(0,2)?($("header").find(".accesskey").attr("title","\u4e0a\u65b9\u529f\u80fd\u5340\u584a"),$(".main").find(".accesskey").attr("title","\u4e2d\u592e\u5167\u5bb9\u5340\u584a"),$("footer").find(".accesskey").attr("title",
"\u4e0b\u65b9\u529f\u80fd\u5340\u584a"),$(".search").find(".accesskey").attr("title","\u95dc\u9375\u5b57\u641c\u5c0b\uff1a\u6587\u7ae0\u95dc\u9375\u5b57\u641c\u5c0b")):"zh"!==d.substring(0,2)&&($("header").find(".accesskey").attr("title","header"),$(".main").find(".accesskey").attr("title","content"),$("footer").find(".accesskey").attr("title","footer"),$(".search").find(".accesskey").attr("title","search"));$("a.goCenter").keydown(function(a){13==a.which&&($("#aC").focus(),$("html, body").stop(!0,
!0).animate({scrollTop:$(".main").find(".accesskey").offset().top},800,"easeOutExpo"))});$(".language").find("ul").hide();d=$(".language").children("a");d.off().click(function(a){$(this).next("ul").stop(!0,!0).slideToggle();a.preventDefault()});d.keyup(function(){$(this).next("ul").stop(!0,!0).slideDown()});$(".language").find("ul li:last>a").focusout(function(){$(".language").find("ul").hide()});$(document).on("touchend click",function(a){$(a.target).is(".language a")||$(".language").find("ul").hide()});
$("table").each(function(a,b){0==$(this).parents(".table_list").length&&0==$(this).parents(".fix_th_table").length&&0==$(this).parent("form").length&&$(this).scroltable()});$(".scroltable-nav-left").append('<div class="tablearrow_left" style="display:none;"></div>');$(".scroltable-nav-right").append('<div class="tablearrow_right"  style="display:none;"></div>');$(window).scroll(function(a){k()});var J;g.scroll(function(){clearTimeout(J);J=setTimeout(function(){k()},50)});(function(){$(".table_list").find("table").each(function(){var a=
$(this).find("tr");rowCount=a.length;for(var b=1;b<=rowCount;b++)$(this).find("th").each(function(c){var d=$(this).text();a.eq(b).find("td").eq(c).attr("data-title",d)})})})();new LazyLoad({elements_selector:"img.lazy",placeholder:"/images/basic/placeholder.gif",effect:"fadeIn",fadeTime:600,threshold:0})});
